# Generated by Django 3.2.7 on 2021-10-01 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_medicine', models.BooleanField(default=False, verbose_name='Can Add Medicine?')),
                ('can_edit_medicine', models.BooleanField(default=False, verbose_name='Can Edit Medicine?')),
                ('can_delete_medicine', models.BooleanField(default=False, verbose_name='Can Delete Medicine?')),
                ('can_add_stock', models.BooleanField(default=False, verbose_name='Can Add Stock?')),
                ('can_edit_stock', models.BooleanField(default=False, verbose_name='Can Edit Stock?')),
                ('can_delete_stock', models.BooleanField(default=False, verbose_name='Can Delete Stock?')),
                ('can_add_sales', models.BooleanField(default=False, verbose_name='Can Make Sales?')),
                ('can_edit_sales', models.BooleanField(default=False, verbose_name='Can Change Sales?')),
                ('can_delete_sales', models.BooleanField(default=False, verbose_name='Can Remove Sales?')),
                ('can_add_salesman', models.BooleanField(default=False, verbose_name='Can Add Salesman?')),
                ('can_delete_salesman', models.BooleanField(default=False, verbose_name='Can Delete Salesman?')),
                ('can_edit_salesman', models.BooleanField(default=False, verbose_name='Can Modify Salesman?')),
                ('can_lock_salesman', models.BooleanField(default=False, verbose_name='Can Block Salesman?')),
                ('can_generate_report', models.BooleanField(default=False, verbose_name='Can Print Report?')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Boss')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pharmaProfile.profilepermission', verbose_name='Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('expense_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
