# Generated by Django 3.2.7 on 2021-10-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaProfile', '0002_alter_profile_permision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permision',
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_medicine',
            field=models.BooleanField(default=False, verbose_name='Can Add Medicine?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_sales',
            field=models.BooleanField(default=False, verbose_name='Can Make Sales?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_salesman',
            field=models.BooleanField(default=False, verbose_name='Can Add Salesman?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_add_stock',
            field=models.BooleanField(default=False, verbose_name='Can Add Stock?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_medicine',
            field=models.BooleanField(default=False, verbose_name='Can Delete Medicine?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_sales',
            field=models.BooleanField(default=False, verbose_name='Can Remove Sales?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_salesman',
            field=models.BooleanField(default=False, verbose_name='Can Delete Salesman?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_delete_stock',
            field=models.BooleanField(default=False, verbose_name='Can Delete Stock?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_medicine',
            field=models.BooleanField(default=False, verbose_name='Can Edit Medicine?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_sales',
            field=models.BooleanField(default=False, verbose_name='Can Change Sales?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_salesman',
            field=models.BooleanField(default=False, verbose_name='Can Modify Salesman?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_edit_stock',
            field=models.BooleanField(default=False, verbose_name='Can Edit Stock?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_generate_report',
            field=models.BooleanField(default=False, verbose_name='Can Print Report?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_lock_salesman',
            field=models.BooleanField(default=False, verbose_name='Can Block Salesman?'),
        ),
        migrations.DeleteModel(
            name='ProfilePermission',
        ),
    ]
