# Generated by Django 3.2.7 on 2021-09-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expire_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('buying_price', models.IntegerField()),
                ('Selling_price', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('added_by', models.CharField(max_length=255)),
                ('medicine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
    ]
