# Generated by Django 3.2.7 on 2021-10-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0002_remove_stock_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
