# Generated by Django 3.2.7 on 2021-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0003_alter_stock_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
