# Generated by Django 3.2.7 on 2021-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0004_alter_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='purchase',
            name='selling_price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='stock_name',
            field=models.CharField(default='pando', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
