# Generated by Django 3.2.7 on 2021-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0006_auto_20211001_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
