# Generated by Django 3.2.7 on 2021-10-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0007_auto_20211001_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Selling_price',
            new_name='selling_price',
        ),
    ]
