# Generated by Django 3.2.7 on 2021-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStock', '0008_rename_selling_price_stock_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
