# Generated by Django 3.2.7 on 2021-10-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True, verbose_name='identifier')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MedicineForm',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('discount', models.IntegerField(default=0)),
                ('side_effect', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True, verbose_name='identifier')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.category')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicineform')),
            ],
        ),
    ]
