# Generated by Django 3.2.7 on 2021-10-01 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
