# Generated by Django 3.2.7 on 2021-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='identifier'),
        ),
    ]
