# Generated by Django 3.2.7 on 2021-09-30 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mode_of_payment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('NHIF_no', models.CharField(max_length=255)),
                ('mode_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.modeofpayment')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('medicine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('payment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.payment')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
